### ISSUE TITLE
How sensitive is the correcting software?

### ISSUE THREAD

**Issue by btn636** [isdsucph/isds2023#2]
Hi Felix,

How sensitive is the correcting software? I have solved ass.0, but now i'm wondering, if I should delete some of my print statements, that I have used to check my answers?

For instance:

**Ex. 0.3.1:**  Write a function called `minimum` that takes as input a list of numbers, and returns the index and value of the minimum number as a `tuple`. Use your function to calculate the index and value of the minimum number in the list `[-342, 195, 573, -234, 762, -175, 847, -882, 153, -22]`. 
Store the result of this computation in a variable named `answer_031`.

#Code that solves Ex. 0.3.1
answer_031 = minimum(numbers_list)

print(answer_031)

Will the print statement here cause a problem?

Best regards,

**Comment by fchop** [comment]
Don't worry. The evaluation will work as long as the result stored in `answer_031` is correct.
