### ISSUE TITLE
did not find TMAX data in df_weather

### ISSUE THREAD

**Issue by didiqra** [isdsucph/isds2023#3]
I tried to write this code:
# Specify the URL of the CSV file for 1863 weather data
url = 'https://www1.ncdc.noaa.gov/pub/data/ghcn/daily/by_year/1863.csv.gz'

# Read the CSV file into the DataFrame df_weather
df_weather = pd.read_csv(url, header=None, compression='gzip')

# Display the first few rows of the DataFrame to verify the data
print(df_weather.head(10))

df_weather.to_csv('weather_data_1863.csv', index=False)

# Define the column names to be used for the selected columns
cols = ['station', 'datetime', 'obs_type', 'obs_value']

# Select the four left-most columns and rename them
df_weather = df_weather.iloc[:, :4].rename(columns=dict(zip(df_weather.columns[:4], cols)))

# Display the first few rows of the DataFrame to verify the changes
print(df_weather.iloc[:, :4])

df_select = df_weather[(df_weather['station'] == 'ITE00100550') & (df_weather['obs_type'] == 'TMAX')].copy()
print(df_select)

but in the end, I can not find the TMAX value. The output of my last code was:
Empty DataFrame
Columns: [station, datetime, obs_type, obs_value]
Index: []

Could you please help me?

**Comment by JonathanIsaksen** [comment]
NOAA changed the dataset after the assignment was posted and the weather station 'ITE00100550' no longer has TMAX, your code is perfectly fine :)

Felix sent out an announcement and updated the assignment on GitHub I recommend downloading the assignment and replacing the section "Changing and Copying Data" with the new one.
It's now station 'EZE00100082' and some of the checks for that part have been updated.
